import { Hobby } from '../types';

export const PRESET_HOBBIES: Hobby[] = [
  {
    id: 'chess',
    name: 'Chess',
    category: 'games',
    icon: '♟️',
    description: 'Master the game of kings',
  },
  {
    id: 'guitar',
    name: 'Guitar',
    category: 'music',
    icon: '🎸',
    description: 'Strum your way to great music',
  },
  {
    id: 'poker',
    name: 'Poker',
    category: 'games',
    icon: '🃏',
    description: 'Learn to read the table',
  },
  {
    id: 'cooking',
    name: 'Cooking',
    category: 'cooking',
    icon: '👨‍🍳',
    description: 'Create delicious meals at home',
  },
  {
    id: 'photography',
    name: 'Photography',
    category: 'art',
    icon: '📷',
    description: 'Capture stunning moments',
  },
  {
    id: 'drawing',
    name: 'Drawing',
    category: 'art',
    icon: '✏️',
    description: 'Bring your imagination to life',
  },
  {
    id: 'yoga',
    name: 'Yoga',
    category: 'fitness',
    icon: '🧘',
    description: 'Find balance and flexibility',
  },
  {
    id: 'piano',
    name: 'Piano',
    category: 'music',
    icon: '🎹',
    description: 'Play beautiful melodies',
  },
  {
    id: 'swimming',
    name: 'Swimming',
    category: 'sports',
    icon: '🏊',
    description: 'Glide through the water',
  },
  {
    id: 'painting',
    name: 'Painting',
    category: 'art',
    icon: '🎨',
    description: 'Express yourself with color',
  },
  {
    id: 'coding',
    name: 'Coding',
    category: 'tech',
    icon: '💻',
    description: 'Build things with code',
  },
  {
    id: 'gardening',
    name: 'Gardening',
    category: 'outdoor',
    icon: '🌱',
    description: 'Grow your own green space',
  },
];
